### ISSUE TITLE
How write data to device?

### ISSUE THREAD

**Issue by uporotayapanda** [MelbourneDeveloper/Device.Net#86]
I write code from example, but it doesn't work...

Exception:

System.AggregateException: One or more errors occurred. (An error occurred while attempting to write to the device) ---> System.IO.IOException: An error occurred while attempting to write to the device ---> System.IO.IOException: IO operation will not work.
 Most likely the file will become too long or the handle was not opened to support synchronous IO operations.
   at System.IO.FileStream.WriteCore(ReadOnlySpan`1 source)
   at System.IO.FileStream.WriteSpan(ReadOnlySpan`1 source)
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at System.IO.Stream.<>c.<BeginWriteInternal>b__49_0(Object <p0>)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.IO.Stream.EndWrite(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__60_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Hid.Net.Windows.WindowsHidDevice.WriteReportAsync(Byte[] data, Nullable`1 reportId)
   --- End of inner exception stack trace ---
   at Hid.Net.Windows.WindowsHidDevice.WriteReportAsync(Byte[] data, Nullable`1 reportId)
   at testDeviceNet.Program.Initialize() in D:\test\testDeviceNet\testDeviceNet\Program.cs:line 64
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at testDeviceNet.Program.Main(String[] args) in D:\test\testDeviceNet\testDeviceNet\Program.cs:line 26
---> (Inner Exception #0) System.IO.IOException: An error occurred while attempting to write to the device ---> System.IO.IOException: IO operation will not work. Most likely the file will become too long or the handle was not opened to support synchronous
IO operations.
   at System.IO.FileStream.WriteCore(ReadOnlySpan`1 source)
   at System.IO.FileStream.WriteSpan(ReadOnlySpan`1 source)
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at System.IO.Stream.<>c.<BeginWriteInternal>b__49_0(Object <p0>)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.IO.Stream.EndWrite(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__60_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Hid.Net.Windows.WindowsHidDevice.WriteReportAsync(Byte[] data, Nullable`1 reportId)
   --- End of inner exception stack trace ---
   at Hid.Net.Windows.WindowsHidDevice.WriteReportAsync(Byte[] data, Nullable`1 reportId)
   at testDeviceNet.Program.Initialize() in D:\test\testDeviceNet\testDeviceNet\Program.cs:line 64<---

       class Program
    {
        private const int VendorId = 0x0483;
        private const int ProductId = 0x5711;
        
        
        static void Main(string[] args)
        {
            var logger = new DebugLogger();
            
            WindowsUsbDeviceFactory.Register(logger);
            WindowsHidDeviceFactory.Register(logger);

            try
            {
                Initialize().Wait();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
            
            Console.WriteLine("Hello World!");
        }

        public static async Task Initialize()
        {
            var deviceDefinitions = new List<FilterDeviceDefinition>
            {
                new FilterDeviceDefinition
                {
                    DeviceType = DeviceType.Hid, 
                    VendorId = VendorId, 
                    ProductId = ProductId
                }
            };

            var devices = await DeviceManager.Current.GetDevicesAsync(deviceDefinitions);

            var device = devices.FirstOrDefault();
            
            if (device == null)
                Console.WriteLine("Device not found.");
            else
            {
                var windowsHidDevice = new WindowsHidDevice(device.DeviceId, 64, 64);
                await windowsHidDevice.InitializeAsync();
                
                var buffer = new byte[64];
                buffer[0] = 0x3f;
                buffer[1] = 0x23;
                buffer[2] = 0x23;

                await windowsHidDevice.WriteAsync(buffer);
            }
        }
    }

**Comment by MelbourneDeveloper** [comment]
@UporotayaPanda can I organise a time to remote desktop on your computer with TeamViewer? This weekend? What is your timezone?

**Comment by MelbourneDeveloper** [comment]
@UporotayaPanda Teamviewer?

**Comment by MelbourneDeveloper** [comment]
@UporotayaPanda I will need to close this issue soon. 

Please try the the 3.0 Beta 2 to see if your issue is solved.

**Comment by MelbourneDeveloper** [comment]
@UporotayaPanda this issue will be closed in the next couple of days if I don't hear from you.
